const ticket = [
  {
    id: "TK001",
    machineId: "MC-101",
    priority: "high",
    status: "open",
    problem: "Overheating issue detected",
    details: "The machine is overheating due to a possible coolant leak.",
    createdAt: "11-11-2025",
  },
  {
    id: "TK002",
    machineId: "MC-102",
    priority: "medium",
    status: "in-progress",
    problem: "Unusual vibration patterns",
    details: "The machine is experiencing unusual vibrations that may indicate a mechanical issue.",
    createdAt: "11-11-2025",
  },
  {
    id: "TK003",
    machineId: "MC-103",
    priority: "low",
    status: "resolved",
    problem: "Routine maintenance check",
    details: "The machine underwent a routine maintenance check and all systems are functioning properly.",
    createdAt: "11-11-2025",
  },
  {
    id: "TK004",
    machineId: "MC-104",
    priority: "high",
    status: "open",
    problem: "Pressure sensor malfunction",
    details: "The pressure sensor is malfunctioning and needs to be replaced.",
    createdAt: "11-11-2025",
  },
  {
    id: "TK005",
    machineId: "MC-105",
    priority: "medium",
    status: "in-progress",
    problem: "Oil level low warning",
    details: "The oil level is low and needs to be refilled.",
    createdAt: "01-11-2025",
  },
  {
    id: "TK001",
    machineId: "MC-101",
    priority: "high",
    status: "open",
    problem: "Overheating issue detected",
    details: "The machine is overheating due to a possible coolant leak.",
    createdAt: "10-11-2025",
  },
  {
    id: "TK002",
    machineId: "MC-102",
    priority: "medium",
    status: "in-progress",
    problem: "Unusual vibration patterns",
    details: "The machine is experiencing unusual vibrations that may indicate a mechanical issue.",
    createdAt: "02-11-2025",
  },
  {
    id: "TK003",
    machineId: "MC-103",
    priority: "low",
    status: "resolved",
    problem: "Routine maintenance check",
    details: "The machine underwent a routine maintenance check and all systems are functioning properly.",
    createdAt: "03-11-2025",
  },
  {
    id: "TK004",
    machineId: "MC-104",
    priority: "high",
    status: "open",
    problem: "Pressure sensor malfunction",
    details: "The pressure sensor is malfunctioning and needs to be replaced.",
    createdAt: "12-01-2025",
  },
  {
    id: "TK005",
    machineId: "MC-105",
    priority: "medium",
    status: "in-progress",
    problem: "Oil level low warning",
    details: "The oil level is low and needs to be refilled.",
    createdAt: "11-01-2024",
  },
  {
    id: "TK001",
    machineId: "MC-101",
    priority: "high",
    status: "open",
    problem: "Overheating issue detected",
    details: "The machine is overheating due to a possible coolant leak.",
    createdAt: "15-01-2024",
  },
  {
    id: "TK002",
    machineId: "MC-102",
    priority: "medium",
    status: "in-progress",
    problem: "Unusual vibration patterns",
    details: "The machine is experiencing unusual vibrations that may indicate a mechanical issue.",
    createdAt: "14-01-2025",
  },
  {
    id: "TK003",
    machineId: "MC-103",
    priority: "low",
    status: "resolved",
    problem: "Routine maintenance check",
    details: "The machine underwent a routine maintenance check and all systems are functioning properly.",
    createdAt: "13-09-2025",
  },
  {
    id: "TK004",
    machineId: "MC-104",
    priority: "high",
    status: "open",
    problem: "Pressure sensor malfunction",
    details: "The pressure sensor is malfunctioning and needs to be replaced.",
    createdAt: "12-01-2025",
  },
  {
    id: "TK005",
    machineId: "MC-105",
    priority: "medium",
    status: "in-progress",
    problem: "Oil level low warning",
    details: "The oil level is low and needs to be refilled.",
    createdAt: "11-10-2025",
  },
];

export default ticket;
